const API_BASE_URL = 'http://localhost:5000';
const NANOSECONDS_PY = 1;
const MICROSECONDS_PY = 1000 * NANOSECONDS_PY;
const MILISECONDS_PY = 1000 * MICROSECONDS_PY;
const MILISECONDS_JS = 1;
const SECONDS_JS = MILISECONDS_JS * 1000;
export{API_BASE_URL, MILISECONDS_PY,SECONDS_JS};